# Site settings | 网站设置
title: Terry's Blog
SEOTitle: realTerry的博客 | Terry
header-img: img/home-bg-he.png
email: 
description: "Terry的博客"
keyword: "realTerry, realTerry的博客"
url: "http://realterryxd.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/realTerryXD/realTerryXD.github.io" #code repository | 代码仓库


# Sidebar settings | 侧边栏设置
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Sing the song of your soul"
sidebar-avatar: /img/head.jpg      # 头像





# SNS settings | 社交网络设置
facebook_username: 
github_username: 
zhihu_username:
csdn_username: 




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
# 转换时排除某些文件夹或文件。被排除的文件或文件夹的路径是相对于网站源码目录的，源码目录以外不受影响。
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

Regeneration: true    # 允许文件修改时自动重新生成网站。





# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

# Gitalk
gitalk:
  enable: false    # 是否开启Gitalk评论
  clientID:     4101e9a11f88545ee9b6                        #生成的clientID
  clientSecret: 1d10a62f76cc4c4cc67009f202f37cdd0bc0f4cd    #生成的clientSecret
  repo: https://github.com/realTerryXD/realTerryXD.github.io    #仓库名称
  owner: realTerryXD    # github用户名
  admin: realTerryXD
  id: 'window.location.pathname'
  distractionFreeMode: true # 是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 


# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true


